---

- hosts: all
  become: true
  vars_files: default/vars.yml
  
  tasks: 

  - name: "Initiating Docker installation first as per the OS..." 
    import_tasks: Ansible/docker-install.yml 

  - name: "Installing Kubernetes into the instances"
    import_tasks: Ansible/k8s-install.yaml



 