apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: appk8s
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete", "create", "update"]