apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: appk8s
  name: podcrud
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podcrud-binding-mukesh-appk8s
  namespace: appk8s
subjects:

- kind: User
  name: mukesh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: podcrud # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io